name: Deploy

on:
  push:
    tags:
      - '*'
env:
  APP_NAME: "matiasguzlop.dev"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: ghcr.io/${{ github.repository }}:latest
          tags: ghcr.io/${{ github.repository }}:latest, ghcr.io/${{ github.repository }}:${{ github.sha}}

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.32.4"

      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Set .env content
        env:
          GITHUB_ENV_CONTENT: ${{ secrets.ENV_FILE }}
        run: echo "$GITHUB_ENV_CONTENT" > .env

      - name: Create kubernetes secret from .env file
        run: |
          kubectl delete secret $APP_NAME --ignore-not-found
          kubectl create secret generic $APP_NAME --from-env-file=.env

      - name: Apply manifests
        run: |
          kubectl apply -f k8s
