name: Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: ghcr.io/${{ github.repository }}:latest
          tags: ghcr.io/${{ github.repository }}:latest, ghcr.io/${{ github.repository }}:${{ github.sha}}

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code to send docker compose file
        uses: actions/checkout@v4

      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_PRIV_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.VPS_SSH_USER }}/matiasguzlop.dev"

      - name: Run through SSH 
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_PRIV_KEY }}
          script: |
            echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u matiasguzlop --password-stdin
            cd /home/${{ secrets.VPS_SSH_USER }}/matiasguzlop.dev
            docker compose up -d --force-recreate
